/-
Copyright (c) 2026. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §17-18).
-- Run 'bash gen-root.bash' after adding or removing modules.

import FOL.FOL
import FOL.MetaRules
import FOL.Tactics
import FOL.Theorems.Derived
-- ⚠️ `Theorems.Eq` NO estaba en este barrel (2026‑09‑12, D‑3): se compilaba **sólo**
-- porque `Completeness` lo importaba. Retirar `Completeness` habría roto **20 módulos de
-- ROBINSON_PlusPlus** sin que ningún control lo avisara.
import FOL.Theorems.Eq
import FOL.Theorems.Impl
import FOL.Theorems.Neg
import FOL.Theorems.Quantifiers
import FOL.Deduction
import FOL.Semantics
import FOL.Completeness

-- ⛔⛔ `FOL.Soundness` y `FOL.Compacity` EN CUARENTENA desde el 2026‑09‑11.
-- `soundness : Γ ⊢ f → Γ ⊨ f` es FALSO en presencia de `FOL.MetaRules`, y su
-- combinación con `raa` demuestra `False` SIN HIPÓTESIS. Este barrel importaba
-- los dos a la vez, así que `import FOL` era un módulo INCONSISTENTE.
-- Evidencia compilada y explicación: `cuarentena/README.md`.
