/-
Copyright (c) 2026. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §23, §30–33).
-- Run 'bash gen-root.bash' after adding or removing modules.

import FOL_poli.FOL
import FOL_poli.Tactics
import FOL_poli.Theorems.Derived
import FOL_poli.Theorems.Impl
import FOL_poli.Theorems.Neg
import FOL_poli.Theorems.Quantifiers
import FOL_poli.Deduction
import FOL_poli.Semantics
import FOL_poli.Soundness
import FOL_poli.Completeness
import FOL_poli.Compacity
